=== BastianRC/Daw-Projects/HTML5/T5/Actividad 3/licencia.dtd
<!ELEMENT galicia (licencias)>
<!ELEMENT licencias (licencia+)>
<!ELEMENT licencia (nombre, dni, clase, caduca)>
<!ATTLIST licencia
    num CDATA #REQUIRED
    tipo CDATA #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT clase (#PCDATA)>
<!ELEMENT caduca (#PCDATA)>

=== BastianRC/Daw-Projects/HTML5/T5/Actividad 3/licencia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE galicia SYSTEM "file:/C:/Users/DarkS/Documents/Daw-Projects/HTML5/T5/Actividad%203/licencia.dtd">
<galicia>
  <licencias>
    <licencia tipo="Pesca Maritima de Recreo" num="22">
      <nombre>Prueba Uno</nombre>
      <dni>78128939J</dni>
      <clase>S</clase>
      <caduca>19/12/2022</caduca>
    </licencia>
    
    <licencia tipo="Pesca Maritima de Recreo" num="23">
      <nombre>Prueba Dos</nombre>
      <dni>38154978J</dni>
      <clase>A</clase>
      <caduca>01/12/2022</caduca>
    </licencia>
  </licencias>
</galicia>
