=== BastianRC/Daw-Projects/HTML5/T5/Actividad 1/prestamos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="prestamos"/>  
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="prestamos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos"/>
        <xs:element ref="firma"/>
      </xs:sequence>
      <xs:attribute name="fecha_entrega" type="xs:string" use="required"/>
      <xs:attribute name="fecha_salida" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lector"/>
        <xs:element ref="libro"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="firma" type="xs:string"/>

  <xs:element name="lector">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="apellidos"/>
        <xs:element ref="domicilio"/>
        <xs:element ref="telefono"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="autor"/>
        <xs:element ref="titulo"/>
        <xs:element ref="clasificacion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="nombre" type="xs:string"/>

  <xs:element name="apellidos" type="xs:string"/>

  <xs:element name="domicilio" type="xs:string"/>

  <xs:element name="telefono" type="xs:string"/>

  <xs:element name="autor" type="xs:string"/>

  <xs:element name="titulo" type="xs:string"/>

  <xs:element name="clasificacion" type="xs:string"/>

</xs:schema>

=== BastianRC/Daw-Projects/HTML5/T5/Actividad 1/prestamos.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/DarkS/Documents/Daw-Projects/HTML5/T5/Actividad%201/prestamos.xsd">
  <prestamos id="1" fecha_salida="01/01/2022" fecha_entrega="01/11/2022">
    <datos>
      <lector>
        <nombre>Prueba</nombre>
        <apellidos>Numero Uno</apellidos>
        <domicilio>Calle Falsa 1</domicilio>
        <telefono>678968974</telefono>
      </lector>
      
      <libro>
        <autor>Patrick Rothfuss</autor>
        <titulo>El nombre del viento</titulo>
        <clasificacion>Novela</clasificacion>
      </libro>
    </datos>
    
    <firma>Prueba Numero Uno</firma>
  </prestamos>
</biblioteca>
